import os
from weshare.settings import *
from weshare.secret import *

# DATABASES = {
#     'default': dj_database_url.config(),
# }

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ALLOWED_HOSTS = ['*']
DEBUG = False

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = PRO_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = PRO_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
SOCIAL_AUTH_GITHUB_KEY = PRO_SOCIAL_AUTH_GITHUB_KEY
SOCIAL_AUTH_GITHUB_SECRET = PRO_SOCIAL_AUTH_GITHUB_SECRET