# Generated by Django 3.0.6 on 2020-06-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
    ]
