# Generated by Django 3.0.7 on 2020-06-11 05:23

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20200610_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
